var dorm = {
  "type":"FeatureCollection",
  "features":[
      {"type":"Feature",
      "properties":{
      "S_no":1,
      "Name":"International College",
      "image": "Data/Image/International Kolleg.jpg",
      "HouseNumber": 10, 
      "Street":"Billrothstrasse, 5020 Salzburg, Austria",
      "RoomType":"Single room , Single room in shared flat with 2/3 people, double share room",
      "Rent":"250 to 365",
      "ds": 4.0,
      "DistancefromTechnoZ":7},
      "geometry":
      {"type":"Point","coordinates":[13.071756362915039, 47.77914861037154]}},
      {"type":"Feature",
      "properties":{
      "S_no":2,
      "Name":"Katharina Von Bora",
      "image" : "Data/Image/KaVB.jpg",
      "HouseNumber":10,
      "Street":"Dr. Altmannstrasse, 5020 Salzburg, Austria",
      "RoomType":"Single room, Double room, triple room",
      "Rent":"250 to 300",
      "ds":3.7,
      "DistancefromTechnoZ":6.3},
      "geometry":
      {"type":"Point","coordinates":[13.044934272766113, 47.77896296098424]}},
      {"type":"Feature",
      "properties":
      {"S_no":3,
      "Name":"die WG",
      "image": "Data/Image/WG.jpg",
      "HouseNumber":2,
      "Street":"Saint-Julian-Strasse, 5020 Salzburg, Austria",
      "RooType":"Single apartmnet, two-room apartment, three-room apartment",
      "Rent":"420 to 490",
      "ds":3.0,
      "DistancefromTechnoZ":1.6},
      "geometry":{
      "type":"Point","coordinates":[13.037860, 47.810770 ]}},
      {"type":
      "Feature",
      "properties":{
        "S_no":4,
        "Name":"Franz Von Sales Kolleg",
        "image": "Data/Image/fvsk.jpg",
        "HouseNumber":11,
        "Street":"Robert Preussler Strasse, 5020 Salzburg, Austria ",
        "RoomType":"Single room , Single room in shared flat with 2/3 people, double share room",
        "Rent":"265 to 400",
        "ds":4.8,
        "DistancefromTechnoZ":7.5},
      "geometry":{"type":"Point","coordinates":[13.073617, 47.771868]}},
      {"type":
      "Feature","properties":{
        "S_no":5,
        "Name":"Europa Kolleg",
        "image": "Data/Image/europa_kolleg.jpg",
        "HouseNumber":28,
        "Street":"Robert Preussler Strasse , 5020 Salzburg, Austria",
        "Room Type":"Single room , Single room in shared flat with 2/3 people, double share room",
        "Rent":"290 to 420",
        "ds":4.8,
        "DistancefromTechnoZ":7.4},
      "geometry":{"type":"Point","coordinates":[13.072627, 47.772834]}},
      {"type":
      "Feature","properties":{
        "S_no":6,
        "Name":"Haus Paracelsus",
        "image": "Data/Image/haus_paracelsus.jpg",
        "HouseNumber":10,
        "Street":"Konrad Laib Strasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, Single room with balcony, Studio Apartment with balcony",
        "Rent":"300 to 400",
        "ds":3.0,
        "DistancefromTechnoZ":5.6},
      "geometry":{"type":"Point","coordinates":[13.061808, 47.787575]}},
      {"type":
      "Feature","properties":{
        "S_no":7,
        "Name":"KolpingHaus",
        "image": "Data/Image/kolpinghaus.jpg",
        "HouseNumber":10,
        "Street":"Adolf Kolping Strasse, 5020 Salzburg, Austria",
        "RoomType":"Single room , Double room",
        "Rent":"400 to 550",
        "ds":4.2,
        "DistancefromTechnoZ":1.1},
      "geometry":{"type":"Point","coordinates":[13.036707, 47.821645]}},
      {"type":
      "Feature","properties":{
        "S_no":8,
        "Name":"LehrerHaus",
        "image": "Data/Image/lehrerhaus.jpg",
        "HouseNumber":9,
        "Street":"Hegigasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, double room, Single room in shared apartment with 4 people",
        "Rent":"365 to 380",
        "ds":3.8,
        "DistancefromTechnoZ":6.5},
      "geometry":{"type":"Point","coordinates":[13.033192, 47.793089]}},
      {"type":
      "Feature","properties":{
        "S_no":9,
        "Name":"Paris Lodron Studentheim",
        "image": "Data/Image/Paris Lodron.jpg",
        "HouseNumber":36,
        "Street":"Schallmooser Hauptstrasse, 5020 Salzburg, Austria",
        "RoomType":"Single room large, Single room small, Double sharing room",
        "Rent":"240 to 340",
        "ds":3.6,
        "DistancefromTechnoZ":4.6},
      "geometry":{"type":"Point","coordinates":[13.056421, 47.806804]}},
      {"type":
      "Feature","properties":{
        "S_no":10,
        "Name":"Ojab Haus",
        "image": "Data/Image/Ojab.jpg",
        "HouseNumber":1,
        "Street":"Strubergasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, Double share room",
        "Rent":"250 to 280",
        "ds":3.5,
        "DistancefromTechnoZ":2.3},
      "geometry":{"type":"Point","coordinates":[13.035222, 47.809187]}},
      {"type":
      "Feature","properties":{
        "S_no":11,
        "Name":"Studentheim Leonardo",
        "image": "Data/Image/leonardo.jpg",
        "HouseNumber":20,
        "Street":"Rocklbrunnstrasse, 5020 Salzburg, Austria",
        "RoomType":"Single room large, Single room small, Double sharing room",
        "Rent":"385 to 450",
        "ds":3.5,
        "DistancefromTechnoZ":4.9},
      "geometry":{"type":"Point","coordinates":[13.062734, 47.812425]}},
      {"type":
      "Feature",
      "properties":{
        "S_no":12,
        "Name":"Techno Z studentheim",
        "image": "Data/Image/Techno Z.jpg",
        "HouseNumber":30,
        "Street":"Schillerstrasse, 5020 Salzburg, Austria",
        "RoomType":"Single room",
        "Rent":"From 430 ",
        "ds":4.2,
        "DistancefromTechnoZ":400},
      "geometry":{"type":"Point","coordinates":[ 13.040996789932251, 47.8226785946535]}},
      {"type":
      "Feature","properties":{
        "S_no":13,
        "Name":"Haus Humboldt",
        "image": "Data/Image/haus humboldt.jpg",
        "HouseNumber":3,
        "Street":"Egger Leinz Gasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, Studio Apartment",
        "Rent":"300 to 370",
        "ds":3.9,
        "DistancefromTechnoZ":6.6},
      "geometry":{"type":"Point","coordinates":[13.073075, 47.782254]}},
      {"type":
      "Feature","properties":{
        "S_no":14,
        "Name":"Mozart Studentheim",
        "image": "Data/Image/Mozart.jpg",
        "HouseNumber":19,
        "Street":"Faberstrasse, 5020 Salzburg, Austria",
        "RoomType":"Single room large, Single room small, Double sharing room",
        "Rent":"300 to 450",
        "ds":2.9,
        "DistancefromTechnoZ":1.9},
      "geometry":{"type":"Point","coordinates":[13.043202, 47.808410]}},
      {"type":
      "Feature","properties":{
        "S_no":15,
        "Name":"Haus Merian",
        "image": "Data/Image/hausmerein",
        "HouseNumber":40,
        "Street":"Merianstrasse, 5020 Salzburg, Austria",
        "RoomType":"Single room small, Single room large",
        "Rent":"245 to 250",
        "ds":3.5,
        "DistancefromTechnoZ":2.1},
      "geometry":{"type":"Point","coordinates":[13.0249,47.4842]}},
      {"type":
      "Feature","properties":{
        "S_no":16,
        "Name":"PMU dormitory",
        "image": "Data/Image/PMU.jpg",
        "HouseNumber":11,
        "Street":"Gaswerkgasse, 5020 Salzburg, Austria",
        "RoomType":"Single room",
        "Rent":"380 to 470",
        "ds":3.2,
        "DistancefromTechnoZ":2.1},
      "geometry":{"type":"Point","coordinates":[13.032758, 47.810095]}},
      {"type":
      "Feature","properties":{
        "S_no":17,
        "Name":"Studentheim Hohensalzburg",
        "image": "Data/Image/Hohensalzburg.jpg",
        "HouseNumber":9,
        "Street":"Bergstraße, 5020 Salzburg, Austria",
        "RoomType":"Single room , double room",
        "Rent":"200 to 350",
        "ds":2.2,
        "DistancefromTechnoZ":4.3},
      "geometry":{"type":"Point","coordinates":[13.045778, 47.803311]}},
      {"type":
      "Feature","properties":{
        "S_no":18,
        "Name":"Akademikerhilfe Studentenheim - Schwarzes Rössl ",
        "image": "Data/Image/akademikerhilfe.jpg",
        "HouseNumber":6,
        "Street":"Priesterhausgasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, Double room",
        "Rent":"From 280",
        "ds":2.0,
        "DistancefromTechnoZ":2.5},
      "geometry":{"type":"Point","coordinates":[13.045079, 47.802754]}},
      {"type":
      "Feature","properties":{
        "S_no":19,
        "Name":"home4students Glockengasse -",
        "image": "Data/Image/Home4student.jpg",
        "HouseNumber":"4B",
        "Street":"Glockengasse, 5020 Salzburg, Austria",
        "RoomType":"Single room, Double room",
        "Rent":"270 to 390",
        "ds":4.3,
        "DistancefromTechnoZ":2.8},
      "geometry":{"type":"Point","coordinates":[13.049325, 47.804214]}},
      {"type":
      "Feature","properties":{
        "S_no":20,
        "Name":"Verein Dr Franz Rehrl Studentenheim -",
        "image": "Data/Image/rehrlheim.jpg",
        "HouseNumber":14,
        "Street":"Petersbrunnstraße, 5020 Salzburg, Austria",
        "RoomType":"Single room",
        "Rent":"280 to 300",
        "ds":1.5,
        "DistancefromTechnoZ":4.2},
      "geometry":{"type":"Point","coordinates":[13.051608, 47.794452 ]}}
  ]
  }
      